name: CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    strategy:
      matrix: 
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build 
        run: cargo build

      - name: Test
        run: cargo test
